linters-settings:
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 20

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - goconst
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

run:
  timeout: 10m

  issues-exit-code: 10

  skip-dirs:
    - vendor
